require('packer-config')
require('settings')
require('settings.vale-config')
require('mappings')
require('notify-config')
require('telescope-config')
-- require('ale-config')
require('treesiter-config')
require('nvimtree-config')
-- require('airline-config')

require('limelight-config')
require('guttentags-config')

require('settings.cmp')
require('settings.colorscheme')
require('settings.options')
require('settings.lualine')
require('settings.aerial')
require('lsp')

